### ISSUE TITLE
In the `ops` click handler, it is possible to enter multiple operators

### ISSUE THREAD

**Issue by parent-tobias** [billyhelms24/js-calculator#1]
To reproduce the issue:
type any digit, followed by two operators. The second operator is placed into the stack as though it were the second number, resulting in a `NaN.

**Comment by billyhelms24** [comment]
This issue has been fixed! Now, on operator key press, the stack is checked to see if the most recent selection was an operator. If so, the operator is then changed to the newly pressed one. If not, the value and operator selected are pushed to the stack. Thanks for pointing this out!

Edit: [Here is a link to view the change](https://github.com/billyhelms24/js-calculator/commit/be61f92509a2fc575f67a95b6fc43ede76677c31)
